### ISSUE TITLE
Response should return an array of notes, not an object called "items"

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox-data-node-i2b2-2014#24]
Not 100% sure that there is an issue. There is an issue if the format of the response is different from what is defined in the OpenAPI spec.

![image](https://user-images.githubusercontent.com/3056480/94354323-ed05ad80-002e-11eb-979b-c4b9f80a601e.png)

**Comment by gkowalski** [comment]
The openAPI spec does not define these as "item" or "items" so I propose we remove that from the json.

**Comment by tschaffter** [comment]
Closing this ticket as we will shift to use an Object as the response payload. One property of this objects will be `items` mentioned here. A related ticket will be open soon to request the implementation of paginated results.
