### ISSUE TITLE
Implement results pagination

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox-data-node-i2b2-2014#39]
We want to be able to limit how many objects a client can request. If we don't control this, a request asking for too much data will slow down the response for other requests.

Proposed format for the response payload object:

- count (integer): number of objects included in the page
- items (array): the list (page) of objects
- next (string): URL to request the next page of results
- previous (string): URL to request the previous page of results

**Comment by gkowalski** [comment]
items , count are added.

**Comment by tschaffter** [comment]
> items , count are added.

@gkowalski Can you create a PR that reflects this contribution and reference it here?
